### PR TITLE
Refactor qubit flux and crosstalk routines

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
As the title says
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
image
Just a two quick comments since you are working on this routine:

- we should change the units of measure from Hz to GHz
- the range on the xaxis should be different for each qubit while they appear to be the same

**Comment by Edoardo-Pedicillo** [comment]
>  - we should change the units of measure from Hz to GHz

Done

**Review by andrea-pasquale — COMMENTED** [review]
I just realized that I forgot to push some comments.
They should be easy to fix.

**Review by andrea-pasquale — APPROVED** [review]
Thanks @Edoardo-Pedicillo, LGTM.
If it is easy to fix the coverage could you give it a try?
Otherwise we can just merge.

**Comment by Edoardo-Pedicillo** [comment]
The lost of coverage is due to the anharmonicity that is 0 in the dummy runcard.
https://github.com/qiboteam/qibocal/blob/5011129569ca9233a2b34753eaff35d47a8fb925/src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py#L85-L88
If we change it, we will lose the coverage of the first branch.

**Comment by andrea-pasquale** [comment]
> The lost of coverage is due to the anharmonicity that is 0 in the dummy runcard.
> 
> https://github.com/qiboteam/qibocal/blob/5011129569ca9233a2b34753eaff35d47a8fb925/src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py#L85-L88
> 
> 
> If we change it, we will lose the coverage of the first branch.

I see. Nevermind than. Feel free to merge as soon as you have 2 approvs

**Review by GabrielePalazzo — APPROVED** [review]

**Pull request merged**
