### PR TITLE
Upgrade qibolab to 0.1.6 before release

### PR DESCRIPTION
**Pull request by andrea-pasquale**
To be merged after #689, afterwards we should be able to proceed with the release @scarrazza 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by scarrazza — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
@Edoardo-Pedicillo could you please merge main to test that all latest changes are passing? Afterwards we can merge and proceed with the release @scarrazza

**Comment by scarrazza** [comment]
Shall we keep #684 for the next release?

**Comment by andrea-pasquale** [comment]
> Shall we keep #684 for the next release?

Yes, let's keep it for the next release

**Comment by andrea-pasquale** [comment]
@scarrazza feel free to merge this and proceed with the release

**Comment by scarrazza** [comment]
Thanks @andrea-pasquale !

**Pull request merged**
