### PR TITLE
Error bars in Allxy

### LINKED ISSUE #544: Propagate error bands in all protocols
Now that we have agreed on a prototype for error bands in #532 we should now propagate them in all protocols.

- [x] flipping @Edoardo-Pedicillo 
- [ ] allXY (no beta) @Edoardo-Pedicillo

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
This PR closes #544 

- http://login.qrccluster.com:9000/7dNOKZ1nRfyOor6QjPj5nw==/ (main)
- http://login.qrccluster.com:9000/Uq_jtPLiSNWvZ-QJbRNPYg==/ (pr)

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by Edoardo-Pedicillo** [comment]
http://login.qrccluster.com:9000/c6KCZHASRqCEcs3Vpsac_A==/

**Review by andrea-pasquale — APPROVED** [review]
Thanks @Edoardo-Pedicillo

**Comment by Jacfomg** [comment]
Is it hard to make the error bars able to be switched on and off ?

**Comment by Edoardo-Pedicillo** [comment]
> Is it hard to make the error bars able to be switched on and off ?

Plotly does not provide this option, the only workaround is to plot two scatter plots, one with errors and the other without, 
from my point of view I don't like it, let me know ...

**Pull request merged**
