### PR TITLE
Changing `to_dict` in property

### PR DESCRIPTION
**Pull request by andrea-pasquale**
This PR needs to be merged as soon as we merge qiboteam/qibolab#346, which will change the `to_dict` method into the property `raw`. This should resolve all issues related to the attribute `average` of the `to_dict` method.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
I just tried it and it fixes the issue.
However I had to do a couple of things in the rfsoc driver (merge main and initialize all AveragedResults with from_components).

If you want I can push those changes, the merge was without conflicts

**Comment by andrea-pasquale** [comment]
> I just tried it and it fixes the issue. However I had to do a couple of things in the qibolab PR (merge main and initialize all AveragedResults with from_components in the rfsoc driver).
> 
> If you want I can push those changes, the merge was without conflicts

Thanks for the feedback @rodolfocarobene.
Feel free to push those changes in qiboteam/qibolab#346.

**Review by Edoardo-Pedicillo — APPROVED** [review]
Thank @andrea-pasquale

**Comment by Edoardo-Pedicillo** [comment]
I confirm that it works with dummy.

**Comment by andrea-pasquale** [comment]
@stavros11 I would like to merge this but I'm not able to test it on QM since I don't know exactly what branch to use. I know that the runcard is in qiboteam/qibolab#349 and that you started from `main` with qiboteam/qibolab#361, however this branch works with qiboteam/qibolab#346 which is also pointing to main.
Given that qiboteam/qibolab#346 does not introduce major changes if you agree we could merge it to main and you can later test it on qiboteam/qibolab#349 or qiboteam/qibolab#361.

**Comment by stavros11** [comment]
@andrea-pasquale I wanted to test it yesterday but unfortunately the QM went out and as far as I know we have not been able to connect to it yet. I am not sure when it will be back but at this stage we could merge this and qiboteam/qibolab#346 and if something breaks for QM I’ll fix it in one of my other open PRs in qibolab.

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale I wanted to test it yesterday but unfortunately the QM went out and as far as I know we have not been able to connect to it yet. I am not sure when it will be back but at this stage we could merge this and [qiboteam/qibolab#346](https://github.com/qiboteam/qibolab/pull/346) and if something breaks for QM I’ll fix it in one of my other open PRs in qibolab.

Thanks. I'll proceed with the merge as soon as we merge [qiboteam/qibolab#346](https://github.com/qiboteam/qibolab/pull/346).

**Pull request merged**
