### PR TITLE
Implement update on qubit_tracking protocol

### PR DESCRIPTION
**Pull request by andrea-pasquale**
As title says

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
@DavidSarlle if you have already some data you can that the update/fit is working by running
```sh
qq fit <output_folder>
```
keep in mind that in this way you will overwrite the results stored in your folder.

**Comment by andrea-pasquale** [comment]
@DavidSarlle whenever you have time let me know if in this PR the update works properly for you.

**Comment by DavidSarlle** [comment]
> @DavidSarlle whenever you have time let me know if in this PR the update works properly for you.

@andrea-pasquale it works as expected. Thanks for update the qubit tracking  code with the update changes

**Comment by andrea-pasquale** [comment]
Thank you @DavidSarlle

**Pull request merged**
