### PR TITLE
Fixing rabi issue when fitting fails 

### LINKED ISSUE #758: Rabi amplitude error-handling
Hey, I believe that there is a "bug" in rabi_amplitude. Basically if the fit fails than an error is raised (not the standard warning).
This is because the `durations` variable is uninitialized (if curve_fit fails). I believe we should try to initialize it before (?)

Or at least I think that this is the problem. Please tell me if this is a driver problem (@andrea-pasquale)

I leave below the full error

```
[Qibo 0.2.4|INFO|2024-03-20 13:52:11]: Minimal execution time (sweep): 1.0448896
[Qibocal 0.0.8|INFO|2024-03-20 13:52:12]: Finished acquisition in 1.18 seconds
/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:94
5: RuntimeWarning: divide by zero encountered in divide
  transform = 1.0 / sigma
[Qibocal 0.0.8|WARNING|2024-03-20 13:52:12]: Rabi fit failed for qubit 0 due to Resid
uals are not finite in the initial point..
Traceback (most recent call last):
  File "/home/rodolfo/Venv/qibo/bin/qq", line 8, in <module>
    sys.exit(command())
             ^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 115
7, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 107
8, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 168
8, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 143
4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 783
, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/_base.py", line 72, in auto
    autocalibrate(runcard, folder, force, update)
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/autocalibration.py", line 56,
 in autocalibrate
    for _ in executor.run(mode=ExecutionMode.autocalibration):
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/execute.py", line 142, in ru
n
    completed = task.run(
                ^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/task.py", line 135, in run
    completed.results, completed.results_time = operation.fit(completed.data)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/operation.py", line 41, in w
rapper
    out = func(*args, **kwds)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/protocols/characterization/rabi/a
mplitude.py", line 171, in _fit
    return RabiAmplitudeResults(pi_pulse_amplitudes, durations, fitted_parameters, ch
i2)
                                                     ^^^^^^^^^
UnboundLocalError: cannot access local variable 'durations' where it is not associate
d with a value
```

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #758

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by rodolfocarobene — APPROVED** [review]

**Comment by rodolfocarobene** [comment]
Tested it, it fails gracefully now :-)

**Comment by rodolfocarobene** [comment]
However I think that also T1 may have a similar problem...
Let me finish testing all the routines and I will come back to you (I'm testing without being connected to anything so they fail immediately)

**Comment by rodolfocarobene** [comment]
for T1 I got:

```
[Qibocal 0.0.8|INFO|2024-03-20 14:23:46]: Finished acquisition in less than 1 second.
/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:94
5: RuntimeWarning: divide by zero encountered in divide
  transform = 1.0 / sigma
[Qibocal 0.0.8|WARNING|2024-03-20 14:23:46]: Exponential decay fit failed for qubit 0
 due to Residuals are not finite in the initial point.
Traceback (most recent call last):
  File "/home/rodolfo/Venv/qibo/bin/qq", line 8, in <module>
    sys.exit(command())
             ^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 115
7, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 107
8, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 168
8, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 143
4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 783
, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/_base.py", line 72, in auto
    autocalibrate(runcard, folder, force, update)
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/autocalibration.py", line 56,
 in autocalibrate
    for _ in executor.run(mode=ExecutionMode.autocalibration):
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/execute.py", line 69, in run
    completed = task.run(
                ^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/task.py", line 112, in run
    completed.results, completed.results_time = operation.fit(completed.data)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/operation.py", line 41, in w
rapper
    out = func(*args, **kwds)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/protocols/characterization/cohere
nce/t1.py", line 136, in _fit
    chi2 = {
           ^
  File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/protocols/characterization/cohere
nce/t1.py", line 140, in <dictcomp>
    utils.exp_decay(data[qubit].wait, *fitted_parameters[qubit]),
                                       ~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 0
```

Then I got an error for `ramsey_sequences` (that does not exist anymore), so we should update the example runcard.

All other routines worked as expected

**Comment by andrea-pasquale** [comment]
> for T1 I got:
> 
> ```
> [Qibocal 0.0.8|INFO|2024-03-20 14:23:46]: Finished acquisition in less than 1 second.
> /home/rodolfo/Venv/qibo/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py:94
> 5: RuntimeWarning: divide by zero encountered in divide
>   transform = 1.0 / sigma
> [Qibocal 0.0.8|WARNING|2024-03-20 14:23:46]: Exponential decay fit failed for qubit 0
>  due to Residuals are not finite in the initial point.
> Traceback (most recent call last):
>   File "/home/rodolfo/Venv/qibo/bin/qq", line 8, in <module>
>     sys.exit(command())
>              ^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 115
> 7, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 107
> 8, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 168
> 8, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 143
> 4, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/lib/python3.11/site-packages/click/core.py", line 783
> , in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/_base.py", line 72, in auto
>     autocalibrate(runcard, folder, force, update)
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/cli/autocalibration.py", line 56,
>  in autocalibrate
>     for _ in executor.run(mode=ExecutionMode.autocalibration):
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/execute.py", line 69, in run
>     completed = task.run(
>                 ^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/task.py", line 112, in run
>     completed.results, completed.results_time = operation.fit(completed.data)
>                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/auto/operation.py", line 41, in w
> rapper
>     out = func(*args, **kwds)
>           ^^^^^^^^^^^^^^^^^^^
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/protocols/characterization/cohere
> nce/t1.py", line 136, in _fit
>     chi2 = {
>            ^
>   File "/home/rodolfo/Venv/qibo/qibocal/src/qibocal/protocols/characterization/cohere
> nce/t1.py", line 140, in <dictcomp>
>     utils.exp_decay(data[qubit].wait, *fitted_parameters[qubit]),
>                                        ~~~~~~~~~~~~~~~~~^^^^^^^
> KeyError: 0
> ```
> 
> Then I got an error for `ramsey_sequences` (that does not exist anymore), so we should update the example runcard.
> 
> All other routines worked as expected

Also T2, SpinEcho and Zeno had the same issues. Try now.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Pull request merged**
