### PR TITLE
Solve missing plot for protocols involving chi2

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Fixing issue spotted by @igres26 in https://github.com/qiboteam/qibolab_platforms_qrc/pull/119#issuecomment-1975121779.
The problem was caused by a side effect introduced in #707.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by igres26 — APPROVED** [review]
This has fixed the issue for me.

**Comment by igres26** [comment]
Although this makes the plot appear again, which fixes the issue, I have got some instances of a reported value of chi2 of around 10^27, which just doesn't seem right.

**Comment by andrea-pasquale** [comment]
> Although this makes the plot appear again, which fixes the issue, I have got some instances of a reported value of chi2 of around 10^27, which just doesn't seem right.

Fixed in https://github.com/qiboteam/qibocal/pull/744/commits/cfd1c08d9dab10ba62dd21a68364367a71864d90.

**Review by stavros11 — APPROVED** [review]
Thanks, seems to work for the resonator spectroscopy (http://login.qrccluster.com:9000/Li931HqmSzO2xCvEhTwtmw==) but only together with #742.

**Comment by andrea-pasquale** [comment]
> Thanks, seems to work for the resonator spectroscopy (http://login.qrccluster.com:9000/Li931HqmSzO2xCvEhTwtmw==) but only together with #742.

Indeed, probably I could have made one PR point to the other. Thanks for checking!

**Pull request merged**
