### PR TITLE
Updating mechanism to dump platforms

### PR DESCRIPTION
**Pull request by andrea-pasquale**
This updates the mechanism to dump platforms modified by https://github.com/qiboteam/qibolab/pull/758

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Given that tests are passing only here after updating the `poetry.lock` (because of https://github.com/qiboteam/qibolab/pull/758). I suggest to merge in the following order:

#698 -> #679 -> #688

In this way we should be able to merge to main without breaking CI.

**Comment by alecandido** [comment]
> Given that tests are passing only here after updating the `poetry.lock` (because of [qiboteam/qibolab#758](https://github.com/qiboteam/qibolab/pull/758)). I suggest to merge in the following order:
> 
> #698 -> #679 -> #688
> 
> In this way we should be able to merge to main without breaking CI.

As usual, I'd rather avoid merging PRs in other PRs, because otherwise you will have to review the code twice (so the original changes will be masked by those already approved).

Can't we just merge this in `main`?

**Comment by andrea-pasquale** [comment]
> As usual, I'd rather avoid merging PRs in other PRs, because otherwise you will have to review the code twice (so the original changes will be masked by those already approved).

I was suggesting just because each PRs contains very small changes.


> Can't we just merge this in `main`? I mean, after rebasing on main just the three commits of this PR.

This is also an option. You mean to close the other two PRs and merge this one directly in main?

**Comment by alecandido** [comment]
> This is also an option. You mean to close the other two PRs and merge this one directly in main?

I didn't know they were small. If they are, we could even do that.

No, my idea was to use `git rebase -i main`, and only retain the last 3 commits, that are those only present in this PR.
I.e. instead of merging the full stack in `main` in a single shot (reviewing altogether or step by step), we could revert the order of the commits.

However, if they are few changes, just merge all of them in a single PR, i.e. merge this one and #679 in #688, and then merge #688, or equivalently close the other two and point this to `main`.

**Comment by andrea-pasquale** [comment]
> However, if they are few changes, just merge all of them in a single PR, i.e. merge this one and #679 in #688, and then merge #688, or equivalently close the other two and point this to `main`.

I see, let me merge everything into #688 and then merge that to main. Thanks!

**Pull request merged**
