### PR TITLE
Set platform in RB backend

### PR DESCRIPTION
**Pull request by alecandido**
This is a rough patch for the problem found in https://github.com/qiboteam/qibolab_platforms_qrc/pull/151#issuecomment-2233114264

A better solution is postponed to a different version of Qibolab/Qibocal.

### CODE REVIEW

**Review by andrea-pasquale — COMMENTED** [review]
Thanks @alecandido, it works for me.
Btw, there are other protocols which are using `GlobalBackend`. I can push directly here the changes or open a new PR adding the same modification for those protocols.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by alecandido** [comment]
> Btw, there are other protocols which are using `GlobalBackend`. I can push directly here the changes or open a new PR adding the same modification for those protocols.

Feel free to push changes, if you wish.
The scope is meaningful, and the PR is definitely not big already.

**Comment by andrea-pasquale** [comment]
> > Btw, there are other protocols which are using `GlobalBackend`. I can push directly here the changes or open a new PR adding the same modification for those protocols.
> 
> @andrea-pasquale feel free to push changes, if you wish. The scope is meaningful, and the PR is definitely not big already.

I've pushed the changes here #943

**Comment by alecandido** [comment]
> I've pushed the changes here #943

Then I'm merging this (it's still in another PR, and it will be needed to make that work)

**Pull request merged**
