### PR TITLE
adding attenuation

### PR DESCRIPTION
**Pull request by maxhant**
adding attenuation important for characterization and removing fixme which is unnecessary

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]
Thanks @maxhant. 
Looks good to me.

**Comment by DavidSarlle** [comment]
@maxhant from the point the view of the code I have no objection regarding the changes. It works as expected. 

From the point of view of the platform design. In my opinion, only the parameters wich the experimentalist wants to play with in the routine in order to  find the best value after run and fit the results should be passed to the script. 
If the parameter is something pre decided in advance and somehow "static", it should be modified directly in the platform runcard. 

Let's see the opinion of the rest.

**Comment by DavidSarlle** [comment]
Also @maxhant , just a comment/curiosity. If we increase the attenuation too much, the results are goin to be quite weak. If you use HW demodulation, the arithmetic precision of the qblox fpga is going to be affected, loosing precission. Is the 46db att an example or is it the correct value for the qubit 3?

**Comment by maxhant** [comment]
> Let's see the opinion of the rest.

No need to get everyone's opinions on tiny details. I will close the PR.

**Pull request closed without merging**
