### PR TITLE
New features pending on qibolab PR#161 (alvaro/binning_pr)

### PR DESCRIPTION
**Pull request by aorgazf**
This PR includes the following new features and fixes:

*Reports*
- Added **qq-compare** command
- Added report concatenation and visualization of saved reports
- Added `Data.load_data_from_dict()` to allow loading a Dataframe at once from a dictionary, instead of row by row.

*Characterisation Routines*
- Added `calibrate_qubit_states_binning()`, which uses binned acquisition to calibrate qubit states. 
- Added a `calibrate_qubit_states` fitting function that calculates: 
  - `rotation_angle` in degrees (0 to 360):The rotation angle that would need to be applied so that the mean of state 0 and the mean of state 1 are both on a horizontal line.
  - `threshold` in V: The threshold is the `i` component voltage that better discriminates between the two states once rotated, the one that gives the greatest fidelity.
- Several enhancements to `qubit_states()` plotting function
image

- Added spin echo characterization routine
- Added sping echo fitting method
- Removed temporary FIXME from all characterization routines to set the LO_frequency. `platform.reload_settings()` takes care of it.
- Added MZ_freq (Intermidiate Frquency for RO pulses) during resonator espectroscopies
- Minor fix in Ramsey detuned iteration
- Minor fixes

### CODE REVIEW

**Comment by aorgazf** [comment]
Hi @scarrazza, @stavros11, @andrea-pasquale. I don't understand why pylint is failing this initialisation of the `PulseSequence` object. Are we not supposed to use variable number of arguments? (`*args`)

Class initialisation:
```python
class PulseSequence:
    def __init__(self, *pulses):
        self.pulses = []  #: list[Pulse] = []
        self.add(*pulses)
```
Instantiation:
```python
    ro_pulse = platform.create_qubit_readout_pulse(qubit, start=RX_pulse.duration)
    gnd_sequence = PulseSequence(ro_pulse) # <- pylint fails here
```

Error thrown:
```
************* Module qibocal.calibrations.characterization.calibrate_qubit_states
src/qibocal/calibrations/characterization/calibrate_qubit_states.py:49:19: E1121: Too many positional arguments for constructor call (too-many-function-args)
src/qibocal/calibrations/characterization/calibrate_qubit_states.py:166:19: E1121: Too many positional arguments for constructor call (too-many-function-args)
```

I can easily fix it with:
```python
gnd_sequence = PulseSequence()
gnd_sequence.add(ro_pulse)
```
but I don't understand why the shorter version is considered to be wrong.

**Comment by andrea-pasquale** [comment]
> Hi @scarrazza, @stavros11, @andrea-pasquale. I don't understand why pylint is failing this initialisation of the `PulseSequence` object. Are we not supposed to use variable number of arguments? (`*args`

Yeah, probably pylint does not like to have a variable number of arguments.

**Review by andrea-pasquale — COMMENTED** [review]
Thanks @aorgazf, could you please update the runcard so that I can reproduce your results?

**Comment by aorgazf** [comment]
> 

Hi @andrea-pasquale , I've updated the runcard in qibolab's PR # 192 Improvements to accelerate fidelity measurements (alvaro/faster_fidelity_pr branch)

**Comment by andrea-pasquale** [comment]
> > 
> 
> Hi @andrea-pasquale , I've updated the runcard in qibolab's PR # 192 Improvements to accelerate fidelity measurements (alvaro/faster_fidelity_pr branch)

Hi @aorgazf , thanks.
I meant the runcards in qibocal
https://github.com/qiboteam/qibocal/blob/1b6ca76c5bbbcee6a6ccdd66d5531c7c1b09e507/runcards/actions_qq_5q.yml#L140
https://github.com/qiboteam/qibocal/blob/1b6ca76c5bbbcee6a6ccdd66d5531c7c1b09e507/runcards/actions_qq_1q.yml#L90

They are missing the parameter `shots` I think

**Review by andrea-pasquale — COMMENTED** [review]
Thanks for implementing this @aorgazf.
Please find below some comments.
I've seen that if I try to run `calibrate_qubit_states_binning` on all 4 qubits plotly is not able to render the plots correctly, as you noticed in #108.
I will have a closer look.

**Comment by andrea-pasquale** [comment]
I've added a `do not merge` tag since this branch is working with qiboteam/qibolab#161 which will be soon merged to main.

**Comment by aorgazf** [comment]
Most of the new features of this PR have already been incorporated in main through other PRs, so I close it.

**Comment by aorgazf** [comment]
Hi, I closed it without realising that there were new features added to it.

**Review by andrea-pasquale — APPROVED** [review]

**Pull request merged**
