### PR TITLE
Fix dispersive shift updated frequency

### LINKED ISSUE #430: Dispersive shift
The dispersive shift routine has something wrong.

The plot works, but the updated runcard has the wrong frequency:

image

runcard: 7371399127000000512

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #430.

I've also renamed `Frequency Shift` to `Chi` by dividing the shift by two (hopefully it is correct).

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by rodolfocarobene** [comment]
Tests seems to be failing for unrelated reasons, but the routine now works (and improves the fidelity!)

**Review by rodolfocarobene — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
> Tests seems to be failing for unrelated reasons, but the routine now works (and improves the fidelity!)

I'll have a look at tests now, thanks for the feedback.

**Comment by rodolfocarobene** [comment]
I approved, but obviously this should be merged after the tests pass.
Also, for a future change, I think would be nice to have in the characterization section "readout frequency" AND "resonator frequency"

**Comment by andrea-pasquale** [comment]
> Also, for a future change, I think would be nice to have in the characterization section "readout frequency" AND "resonator frequency"

In theory we already have the information about the readout frequency in the readout pulse.
We should be more careful when updating the runcard. For this particular case I would say that the dispersive shift should only update the frequency of the readout pulse without touching the resonator frequency.
What do you think?

**Comment by rodolfocarobene** [comment]
It makes sense, but then I would change the naming in the characterization section that is now called "readout frequency" to "resonator frequency".
Obviously doesn't change much, but now it's a bit misleading and we "loose" some information

**Comment by andrea-pasquale** [comment]
> It makes sense, but then I would change the naming in the characterization section that is now called "readout frequency" to "resonator frequency". Obviously doesn't change much, but now it's a bit misleading and we "loose" some information

I agree. We already have `bare resonator frequency` even if we are not using it in the runcards I think.
At this point we could have `bare resonator frequency` and `dressed resonator frequency` in the `characterization` section and we keep the readout freq in the pulse.

**Comment by Jacfomg** [comment]
> > Also, for a future change, I think would be nice to have in the characterization section "readout frequency" AND "resonator frequency"
> 
> In theory we already have the information about the readout frequency in the readout pulse. We should be more careful when updating the runcard. For this particular case I would say that the dispersive shift should only update the frequency of the readout pulse without touching the resonator frequency. What do you think?

I think we only care about the readout frequency, we may only store the resonator frequency if we were interested on doing some simulation, right ?

**Comment by andrea-pasquale** [comment]
> I think we only care about the readout frequency, we may only store the resonator frequency if we were interested on doing some simulation, right ?

To run things yes we need only the readout frequency. I would say that there is some value in also storing the resonator frequency.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Review by Jacfomg — APPROVED** [review]

**Pull request merged**
