### PR TITLE
From rtd to furo sphinx theme

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
I have modified the `conf.py` in the doc folder selecting the Furo sphinx theme and setting the colors according to the web site.
When we are ready with the site we can merge this branch.

### CODE REVIEW

**Comment by AleCandido** [comment]
Base the PR on the correct branch, or rebase this branch if required. Here there should be only three commits (2 from Matteo and 1 from pre-commit), but there are too many.

**Comment by andrea-pasquale** [comment]
> Base the PR on the correct branch, or rebase this branch if required. Here there should be only three commits (2 from Matteo and 1 from pre-commit), but there are too many.

Fixed thanks @AleCandido. I wanted to point this PR to `refactor_docs` since it is the branch where we are refactoring the documentation before merging to main. I tried to merge main into refactor_docs but there were still too many commits. For the time being we can point this PR to main.

**Comment by andrea-pasquale** [comment]
Also @MatteoRobbiati remember to add furo to the deps.

**Comment by andrea-pasquale** [comment]
Now everything is correct.

**Comment by MatteoRobbiati** [comment]
> Now everything is correct.

Thank you @andrea-pasquale .

**Comment by andrea-pasquale** [comment]
This PR is ready to merge, correct @MatteoRobbiati?

**Comment by MatteoRobbiati** [comment]
> This PR is ready to merge, correct @MatteoRobbiati?



> This PR is ready to merge, correct @MatteoRobbiati?

Now I think yes. I have just updated the `pyproject.toml` and run the `poetry update`. Please @andrea-pasquale, can you check if all is correct?

**Review by andrea-pasquale — APPROVED** [review]
Thanks @MatteoRobbiati.
Everything works as expected.

**Pull request merged**
