### PR TITLE
Hotfix for rabi length following #744

### PR DESCRIPTION
**Pull request by andrea-pasquale**
In #744 I forgot to update the rabi length protocol.

EDIT: Improved fit for rabi length with probabilities.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
Thanks @andrea-pasquale, I believe it fixes the fitting:
Before: http://login.qrccluster.com:9000/0dk2ahd8RjuAd1tPe_QUHQ==
After: http://login.qrccluster.com:9000/r3dZGTOaRHu21mr0RrNe7A==
(I guess qubit 2 fails in both cases because the signal is not really sinusoidal).

**Comment by andrea-pasquale** [comment]
> Thanks @andrea-pasquale, I believe it fixes the fitting:
> 
> Before: http://login.qrccluster.com:9000/0dk2ahd8RjuAd1tPe_QUHQ==
> 
> After: http://login.qrccluster.com:9000/r3dZGTOaRHu21mr0RrNe7A==
> 
> (I guess qubit 2 fails in both cases because the signal is not really sinusoidal).

Thanks @stavros11. The fix was just to show correctly the fit in the report. I did not touch or improve the performance of the fit. I can have a closer look at qubit 2 before merging.

**Comment by stavros11** [comment]
> Thanks @stavros11. The fix was just to show correctly the fit in the report. I did not touch or improve the performance of the fit. I can have a closer look at qubit 2 before merging.

Well, the minima are clearly more flat than a sinusoidal, so I wouldn't blame the fit for failing in that case. We were just discussing with @rodolfocarobene why this happens but we don't have any idea. The insteresting thing is that this is the qubit that has 97% assignment fidelity...

**Comment by andrea-pasquale** [comment]
Since you have 97% fidelity you could try to run rabi length with probabilities.

**Comment by andrea-pasquale** [comment]
> > Since you have 97% fidelity you could try to run rabi length with probabilities.
> 
> Indeed, looks better but the fit still fails: http://login.qrccluster.com:9000/WfsuyLv_QmKTKPthroPbRQ==

Yeah, there was a problem with the fit. Should be fixed by https://github.com/qiboteam/qibocal/pull/754/commits/6cd7185bea054d07fb1cb802acbeba9933f9df20. Feel free to retry now @stavros11.

Screenshot from 2024-03-18 22-00-15

It turns out that just by normalizing the x axis everything seems to work...

**Review by stavros11 — APPROVED** [review]
It works for me as well, thanks.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Pull request merged**
