### PR TITLE
Update `platform.dump`

### PR DESCRIPTION
**Pull request by stavros11**
Required when qiboteam/qibolab#564 is merged.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [ ] Qibolab: `dumpruncard`
    - [ ] Qibolab_platforms_qrc: `rmruncard`

### CODE REVIEW

**Review by aorgazf — APPROVED** [review]

**Comment by stavros11** [comment]
@scarrazza @AleCandido how do you handle the dependency versions here? This should only work with qibolab v0.1.0 that will probably be released at the end of the week. How should I make the CI pass without pointing to main?

**Comment by rodolfocarobene** [comment]
Test were failing, I've update the lock file and fixed the time of flight routine that was accessing to `platform.sampling_rate`. If tests pass it's ok for me

**Comment by rodolfocarobene** [comment]
> @scarrazza @AleCandido how do you handle the dependency versions here? This should only work with qibolab v0.1.0 that will probably be released at the end of the week. How should I make the CI pass without pointing to main?

It's already pointing to the github repo at the moment

**Comment by stavros11** [comment]
> It's already pointing to the github repo at the moment

Yes, sorry, I just saw this. I thought we were avoiding pointing to main for some reason.

**Review by rodolfocarobene — APPROVED** [review]

**Review by AleCandido — APPROVED** [review]

**Comment by scarrazza** [comment]
Yes, please, keep pointing to main until we release Qibolab 0.1.0.

**Pull request merged**
