### PR TITLE
Removing virtual phase from CZ routine, as it might interfere with the calibration of the virtual phase

### PR DESCRIPTION
**Pull request by igres26**
Just removing the virtual phases set in the creation of the CZ gate from the routine. 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by Edoardo-Pedicillo** [comment]
Thanks @igres26. Could you please upload reports to show the results of this routine before and after the changes in this PR ?

**Review by Edoardo-Pedicillo — APPROVED** [review]
Thanks @igres26 !

**Review by andrea-pasquale — APPROVED** [review]

**Comment by Edoardo-Pedicillo** [comment]
Hi @igres26 , I had a look at the tests and there was a problem with the protocol `optimize_two_qubit_gate` that shares the function `create_sequence` with `virtualz` routine.

https://github.com/qiboteam/qibocal/blob/3c5a42d04abee23c15e37d64e7de48b2c6ef5e9c/src/qibocal/protocols/two_qubit_interaction/optimize.py#L171

The failing of the tests comes from the fact that the dummy platform applies the RZ correction to a pair that is not the one where the gate is applied  

https://github.com/qiboteam/qibolab/blob/171522aabfb606093ecf7ac0c888ae2db134594c/src/qibolab/dummy/parameters.json#L280-L289

In `main`, tests are passing because the `virtual_z_phase` dictionary 

https://github.com/qiboteam/qibocal/blob/74d2625e98435c5f609eedd7002b6d15f35c9b53/src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py#L130

is updated during the creation of the RX90 pulse adding the missing qubit 

https://github.com/qiboteam/qibocal/blob/74d2625e98435c5f609eedd7002b6d15f35c9b53/src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py#L143-L147

Since the `virtual_z_phase` is not used anymore, the dictionary is not updated and `optimize_two_qubit_gate` protocol was giving an error. I will have a better look but I think we can remove `virtual_z_phase` and `data.vphases`.

**Comment by Edoardo-Pedicillo** [comment]
@igres26 Could you test the routine and provide the report ?

**Pull request merged**
