### PR TITLE
New documentation for qibocal

### LINKED ISSUE #103: Completing documentation
In order to provide an useful documentation please find below my wishlist (be free to include more features):
- [x] complete installation instructions. Include CI tests for linux, mac and windows for multiple version of python. So we can tell which configurations are supported.
- [x] complete qq-upload docs
- [ ] include references to real actions names, cleanup examples, include links to examples. Add step by step instructions explaining how to run the code.
- [ ] complete all calibrations by adding proper docstrings with explanation and references and including examples. If possible include some example of plots so people are aware of what expect. Someone new to the topic should understand what each action is doing.
- [ ] add documentation about live plotting, with some examples
- [x] talk about the output data structure, show examples
- [x] update README

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Update `qq` documentation after merging #183

This PR will close #103.
I've started to refactor the documentation for qibocal. I'll try to cover all the points raised in #103.
If there are some issues with qibocal, or if we think that we are missing something in the documentation feel free to comment on this PR or in #103.

### CODE REVIEW

**Comment by MatteoRobbiati** [comment]
Hi @andrea-pasquale , for the first point do you think there are any particular functions to perform or is it enough to use qibocal as "external user" ?

**Comment by andrea-pasquale** [comment]
Hi @MatteoRobbiati, yes, it should be sufficient to add the general instructions on how to install qibocal.
We should add a section `How to calibrate the tii platform` where we can include what we currently have in the `README` (in particular the installation of qibolab using the `tiiq` extra flag). Maybe it is better to put it in a tutorial/example and in the installation instructions we simply add a link to the tutorial, let me know what you think.
We should also include a table with the OS and the version currently supported, something like [this](https://qibo.readthedocs.io/en/stable/getting-started/installation.html#operating-systems-support). Right now, we support all OS from python 3.8 to 3.10.

You made me realize that the README is also outdated, in particular the SSH key part which is no longer required since everything is public now. I'll add that to the wishlist in #103.

**Comment by MatteoRobbiati** [comment]
@andrea-pasquale okay, clear. 
I've just created a branch (`writing_docs`) if you agree, we can use it for working on the documentation.

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale okay, clear.
> I've just created a branch (`writing_docs`) if you agree, we can use it for working on the documentation.

If we agree we can keep this as the "main" branch for the documentation refactor and we can create PRs pointing directly to this one before merging to main. As soon as we have something in the `writings_docs` branch you can open a PR poiting to this one.

**Comment by MatteoRobbiati** [comment]
Perfect, thank you @andrea-pasquale .

**Comment by andrea-pasquale** [comment]
@Edoardo-Pedicillo when you have time could you please have a look at this PR? Mainly fixing conflicts and checking if all the docstrings are shown properly in the documentation.

**Comment by Edoardo-Pedicillo** [comment]
It follows a list of missing descriptions in the documentation:

- [ ] `qibocal.calibrations.characterization.calibrate_qubit_states.calibrate_qubit_states_binning`
- [ ] `qibocal.fitting.methods.spin_echo_fit`
- [ ] `qibocal.fitting.methods.calibrate_qubit_states_fit`
- [ ] `qibocal.calibrations.characterization.qubit_spectroscopy.qubit_spectroscopy_flux_track`
- [ ] add a description of `corrected_qubit_frequency` in `qibocal.calibrations.characterization.ramsey.ramsey_frequency_detuned`
- [ ] add a description of `corrected_qubit_frequency` in `qibocal.calibrations.characterization.ramsey.ramsey`

@DavidSarlle, when you have time, could you help me with the missing ones? Thank you

**Comment by andrea-pasquale** [comment]
I think that this PR is ready to merge.
@scarrazza @stavros11 @MatteoRobbiati @Edoardo-Pedicillo feel free to have a final look.
I would like to merge this even if it can still be improved so that in the website we have a more updated version of the documentation.


> It follows a list of missing descriptions in the documentation:
> 
> * [ ]  `qibocal.calibrations.characterization.calibrate_qubit_states.calibrate_qubit_states_binning`
> * [ ]  `qibocal.fitting.methods.spin_echo_fit`
> * [ ]  `qibocal.fitting.methods.calibrate_qubit_states_fit`
> * [ ]  `qibocal.calibrations.characterization.qubit_spectroscopy.qubit_spectroscopy_flux_track`
> * [ ]  add a description of `corrected_qubit_frequency` in `qibocal.calibrations.characterization.ramsey.ramsey_frequency_detuned`
> * [ ]  add a description of `corrected_qubit_frequency` in `qibocal.calibrations.characterization.ramsey.ramsey`
> 
> @DavidSarlle, when you have time, could you help me with the missing ones? Thank you

Regarding this points, @Edoardo-Pedicillo, let me suggest to open an issue so that we can take care of these small corrections later.

**Review by scarrazza — APPROVED** [review]
Looks good to me, thanks @andrea-pasquale.

**Review by MatteoRobbiati — APPROVED** [review]
Thanks @andrea-pasquale.

**Comment by MatteoRobbiati** [comment]
> I think that this PR is ready to merge. @scarrazza @stavros11 @MatteoRobbiati @Edoardo-Pedicillo feel free to have a final look. I would like to merge this even if it can still be improved so that in the website we have a more updated version of the documentation.

> Regarding this points, @Edoardo-Pedicillo, let me suggest to open an issue so that we can take care of these small corrections later.

I agree with these. It is better to have an updated version od the docs asap.
Thank you very much for your work.

**Pull request merged**
