### PR TITLE
Simplify Ramsey code

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Simplify the Ramsey code as suggested by @igres26 following #337.
This PR will not fix the bug for qblox as it is related to a problem with the relative phase.
I tried to test it this morning with qblox but I think that something is not working.
@Jacfomg could be please rerun quickly the sanity check that we ran yesterday using iqm?

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by Jacfomg** [comment]
Yes, I will do that. But also, we can take another look into why you could not manage to run things yesterday

**Comment by andrea-pasquale** [comment]
I think that it was because I had messed things up with conda.
I will give it another try.

**Comment by Jacfomg** [comment]
This is with this code, @igres26 I also substracted .5 MHz from the qubit frequency and now you see the delta being negative but the correction is still working as intended as we substract it as well

image

**Review by igres26 — APPROVED** [review]
Looks good. We could make it more clear that the sign in the `(-2*np.pi)` is the same as the `-int((delta_fitting...`. Maybe in the comments. But this works.

**Review by Jacfomg — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
Tested and it works both with qblox (commenting a single line) and with RFSoC

**Pull request merged**
