### PR TITLE
Replace qq auto with qq run

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
This choice comes from some internal discussions, the most recent one is https://github.com/qiboteam/xmind-diagrams/pull/31#discussion_r1773509461

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `0.1`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by Edoardo-Pedicillo** [comment]
@scarrazza do you think we can go on with this PR and update the Qibocal-paper before the submission?

**Comment by scarrazza** [comment]
Yes, I agree.

**Review by alecandido — APPROVED** [review]

**Review by andrea-pasquale — APPROVED** [review]
Thanks @Edoardo-Pedicillo.
In theory we need to update the diagram that we have in the qibocal paper also here in the documenation, correct? Maybe it is worth waiting until the diagram is ready to merge the PR.

Also, perhaps we could add a log message when importing the library saying that `qq auto` has been renamed `qq run`? It could also makes sense to do it once we have a release I guess. I'm suggesting this to lower the confusion among users :)

**Comment by alecandido** [comment]
> Also, perhaps we could add a log message when importing the library saying that `qq auto` has been renamed `qq run`? It could also makes sense to do it once we have a release I guess. I'm suggesting this to lower the confusion among users :)

I would exclude doing that at import time (it would appear also in any script not using the CLI), and I'm generally against warnings.

What I may support is to keep the `qq auto` subcommand, just to print a message telling the user to use `qq run` instead.

**Comment by andrea-pasquale** [comment]
> What I may support is to keep the `qq auto` subcommand, just to print a message telling the user to use `qq run` instead.

This could work.

**Review by andrea-pasquale — APPROVED** [review]

**Pull request merged**
