### PR TITLE
Fix bug in rabi 2D fit

### LINKED ISSUE #991: Rabi Amplitude-Frequency fit error
The following Rabi amplitude-frequency protocol produces an incorrect fit result for the optimal Rabi frequency.

[rabi.pdf](https://github.com/user-attachments/files/17220736/rabi.pdf)

report uploaded at: http://login.qrccluster.com:9000/pXEZYz8WT9anjwP5k37vbQ==/

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #991.

I would like to add a test to verify that the code works properly.
I don't know if this is feasible unless we use some regressions.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `0.1`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by alecandido** [comment]
> I would like to add a test to verify that the code works properly.
> I don't know if this is feasible unless we use some regressions.

I believe the best approach (in this and other cases) is truly a closure test: generate the data manually, as you expect they should be, with little or no noise (to make the fit simpler) and check that the fit is able to determine the parameters used in the data generation.

**Review by ElStabilini — APPROVED** [review]

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
Thanks for the approvals. Before merging I want to add a test following @alecandido's suggestion.

**Comment by alecandido** [comment]
> Thanks for the approvals. Before merging I want to add a test following @alecandido's suggestion.

That's a correct approach, and I should encourage it.

However, if this is a bug fix, it may be more practical to just this PR as it is, and lift the suggestion to an issue, such that the test can be introduced as soon as there will be resources available to do that (i.e. decoupling it from the urgency of the bug fix itself).

**Comment by Edoardo-Pedicillo** [comment]
I have opened https://github.com/qiboteam/qibocal/issues/1000 regarding the test issue, so we can merge this PR

**Pull request merged**
