### PR TITLE
Standardize documentation for new layout

### PR DESCRIPTION
**Pull request by andrea-pasquale**
This PR uses the same layout for the documentation already used in other qibo repositories.
Now the API reference is also generated automatically.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
@scarrazza we may also consider removing some outdated documentation related to the RB.
https://github.com/qiboteam/qibocal/tree/new_layout_doc/doc/source/getting-started/niGSC
Mostly because this features are not supported (being able to run protocols without passing through the qibocal API).
I would rather removing it simply because we clean up all the documentation and this is the only old part still present.
Let me know what you think.

**Comment by scarrazza** [comment]
Ok, fine by me.

**Review by Edoardo-Pedicillo — APPROVED** [review]
Thank @andrea-pasquale. LGTM

**Comment by andrea-pasquale** [comment]
> Ok, fine by me.

I removed it now.

**Comment by scarrazza** [comment]
Looks good, could you please add some image in the front-page summarizing the features in qibocal (one of the xmind we already have)?

**Comment by andrea-pasquale** [comment]
I've just added the image.

**Comment by scarrazza** [comment]
Looks good, thanks

**Comment by scarrazza** [comment]
@andrea-pasquale could you please update poetry and make sure the proper release versions of qibolab/qibo, etc. are correct?

**Comment by andrea-pasquale** [comment]
Qibo it is fine, I believe.
For qibolab, do you want the stable release?

**Comment by andrea-pasquale** [comment]
> For qibolab, do you want the stable release?

This could create issues when treating errors later on, given that we will need to merge a PR in qibolab.

**Comment by scarrazza** [comment]
Well, but one of the major points of making a release of qibocal now, is the compatibility with the stable release in qibolab, no? Later we will make another qibolab release and then update this repository.

**Comment by andrea-pasquale** [comment]
> Well, but one of the major points of making a release of qibocal now, is the compatibility with the stable release in qibolab, no? Later we will make another qibolab release and then update this repository.

Sure I will change it to the stable release

**Comment by andrea-pasquale** [comment]
Tests are not passing because we in qibolab we recently merged https://github.com/qiboteam/qibolab/pull/574

**Comment by andrea-pasquale** [comment]
It is my mistake since I merged  #501 which was related to the 0.0.4 release.

**Comment by scarrazza** [comment]
Is it possible to patch qibocal temporarily for the 0.0.3 release, avoiding the usage of this new feature in qibolab?

**Comment by andrea-pasquale** [comment]
> Is it possible to patch qibocal temporarily for the 0.0.3 release, avoiding the usage of this new feature in qibolab?

I can remove it from tests and decrease coverage. Otherwise I will need to revert the PR.

**Comment by scarrazza** [comment]
You can do the following, open another PR with the revert changes, we then merge, make a release and finally you revert.

**Comment by scarrazza** [comment]
Could you please also merge main here?

**Comment by andrea-pasquale** [comment]
Actually I cannot merge it since #512 already started from main. Can I put a merge commit anyway (I'm looking on how to do it).

**Comment by scarrazza** [comment]
Ok, then let's hope that the CI passes.

**Comment by andrea-pasquale** [comment]
@scarrazza after the CI finishes we should be ready to merge . There is only a small decrease in coverage which should be fine I think.

**Comment by scarrazza** [comment]
Sure, lets wait for it.

**Review by scarrazza — APPROVED** [review]

**Pull request merged**
