### PR TITLE
Dropping DAG

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Changing executor to deal only with sequential protocols execution, as discussed in #748.

Given that I'm removing a lot of things that we may want to use later like `Validators` perhaps it would be better to have a development branch... and merge everything to main once we have implemented some/all of the points raised in #748.

This first step was quite straightforwarded to do, this is why I'm already raising the PR.

- [x] update documentation
- [x] update runcards everywhere

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Let me know what you think @stavros11 @Edoardo-Pedicillo @alecandido @hay-k

**Review by alecandido — APPROVED** [review]
It is a breaking change, so all runcards will have to be updated (no problem for those manually written and throw-away, I'm more worried about the monitoring and similar use cases).

But since no one ever used the graph, if you allow for now random keys (`main:`, `next:`, `priority:`, ...) maybe you could preserve compatibility "in practice" (with existing runcards), and merge immediately.

**Comment by andrea-pasquale** [comment]
> But since no one ever used the graph, if you allow for now random keys (`main:`, `next:`, `priority:`, ...) maybe you could preserve compatibility "in practice" (with existing runcards), and merge immediately.

Indeed, this is something that I can do. If we treat them as optional arguments I can also put warning if they are set telling the user that they will be dropped soon and that they are unused from now on.

**Comment by andrea-pasquale** [comment]
@GabrielePalazzo although this PR should not break the monitoring, I updated the monitoring runcard. Let me know if you see any issues.

**Comment by Edoardo-Pedicillo** [comment]
> But since no one ever used the graph, if you allow for now random keys (`main:`, `next:`, `priority:`, ...) maybe you could preserve compatibility "in practice" (with existing runcards), and merge immediately.

Are you sure we should rely on the order of the routines in the runcard, instead of keeping a `next` key? 
Since we are still supporting yaml, I think it is easier to change the value of a key instead of moving around bunch of lines,  to change the order of the routines. Maybe we could keep it for now and eventually drop it later, when we will use the API to calibrate.

**Comment by alecandido** [comment]
> Maybe we could keep it for now and eventually drop it later, when we will use the API to calibrate.

It's defnitely an option. But most of the runcards I've seen are either sorted, and not frequently changing (like the monitoring), or running single routines.
I would also take into account that, unless you're doing it very frequently, moving lines around is not so painful (thanks clipboards), and having large YAML runcards is not adviced (nor happening?)

**Comment by Edoardo-Pedicillo** [comment]
> unless you're doing it very frequently,

I think this is the case, for what I saw, if you calibrate a device and the results are not good :)

**Comment by alecandido** [comment]
> I think this is the case, for what I saw, if you calibrate a device and the results are not good :)

Changing runcard frequently is ok, I understand it. But even changing order? (and are people calibrating with more than one routine at a time?)

**Comment by Edoardo-Pedicillo** [comment]
> But even changing order?

For what I saw, generally a single runcard is used multiple times and to change calibration experiment some parts are commented and uncommented, doing this it happens frequently that the order of routines is not what desired.

>and are people calibrating with more than one routine at a time?

Yes, if the chip is calibrated but you want just to update the platform with the small parameters drifts.

**Comment by alecandido** [comment]
> For what I saw, generally a single runcard is used multiple times and to change calibration experiment some parts are commented and uncommented, doing this it happens frequently that the order of routines is not what desired.

Yes, but if you uncomment a single routine at a time you don't care about the order (and moreover, you're already making changes to your runcard that are comparable to moving things around, the comment button is not much heavier than the cut one...).

> Yes, if the chip is calibrated but you want just to update the platform with the small parameters drifts.

This would have been my initial expectation (month ago), but:
- I've barely seen any report like this on the report server
- it is months since we had an actual calibrated chip...

**Comment by Edoardo-Pedicillo** [comment]
> For what I saw, generally a single runcard is used multiple times and to change calibration experiment some parts are commented and uncommented, doing this it happens frequently that the order of routines is not what desired.

Sorry, here I was referring to the time when DAG was not present.

> * I've barely seen any report like this on the report server

I'm not sure how statistically significant the report server is.

By the way, I don't want to push too much the use of the key, I am just suggesting speaking to the people using Qibocal, because I don't see any particular preference from the software point of view.

**Comment by alecandido** [comment]
> By the way, I don't want to push too much the use of the key, I am just suggesting asking to the people using Qibocal, because I don't see any particular preference from the software point of view.

Eventually, I'd keep the runcard mode for very straightforward usage. That's why I'd make it as simple as possible.
For a transient, we could do whatever. If you believe to be really useful we could keep it, it's just a bit of extra work to maintain it.

**Comment by andrea-pasquale** [comment]
Following today's discussion I decided to drop the warnings, I'm planning to merge it as it is as soon as I get the second approval.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
For dropping `priority`, `main` and `next` from all runcards in a single go here is the regex:

```sh
^[# \t]*(priority|next|main).*?(\n|$)
```

**Pull request merged**
