### PR TITLE
fix: Added json extension to results for singleshot classification

### LINKED ISSUE #746: Missing extension to the results filename for singleshot classification
The results file obtained by the singleshot classification routine is named `results` instead of `results.json`.

Runcard used:

``` yaml
actions:

  - id: t1
    priority: 0
    operation: t1
    main: single_shot_classification
    parameters:
      delay_before_readout_start: 16
      delay_before_readout_end: 2000
      delay_before_readout_step: 20

  - id: single_shot_classification
    priority: 0
    operation: single_shot_classification
    parameters:
      nshots: 1024
```

### PR DESCRIPTION
**Pull request by GabrielePalazzo**
Closes #746.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by andrea-pasquale — COMMENTED** [review]
Thanks @GabrielePalazzo, do you know why tests are failing?

The problem was related to this line:
https://github.com/qiboteam/qibocal/blob/ddba2d3da995a308756ed25a1072b7e230a546ac/src/qibocal/protocols/characterization/classification.py#L127

An alternative solution would be to add `.json` directly in this line.
Maybe it is better to put the extension directly in the top-level-constant.

Let me know what you think.

**Comment by GabrielePalazzo** [comment]
If I revert this line, tests are passing. 
https://github.com/qiboteam/qibocal/blob/e3737a37b9caa307b8042b8da9fd382087f7ed15/src/qibocal/auto/operation.py#L136
The cause is here (when we read json):
https://github.com/qiboteam/qibocal/blob/e3737a37b9caa307b8042b8da9fd382087f7ed15/src/qibocal/auto/operation.py#L169
I think the safest approach is what you suggested (explicitly adding `.json` in singleshot), considering that, for example, `DATAFILE` cannot have its extension (it can be both `json` and `npz`).
What do you think?

**Comment by andrea-pasquale** [comment]
> If I revert this line, tests are passing.
> 
> https://github.com/qiboteam/qibocal/blob/e3737a37b9caa307b8042b8da9fd382087f7ed15/src/qibocal/auto/operation.py#L136
> 
> The cause is here (when we read json):
> 
> https://github.com/qiboteam/qibocal/blob/e3737a37b9caa307b8042b8da9fd382087f7ed15/src/qibocal/auto/operation.py#L169
> 
> I think the safest approach is what you suggested (explicitly adding `.json` in singleshot), considering that, for example, `DATAFILE` cannot have its extension (it can be both `json` and `npz`).
> What do you think?

Sure, let's add `.json` in singleshot I forgot to update it when we refactored the data structure in #690.

**Review by andrea-pasquale — APPROVED** [review]
Thanks @GabrielePalazzo

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Pull request merged**
