### PR TITLE
Adjusting flux spectroscopy report

### LINKED ISSUE #473: Formatting Results - Flux Spectroscopies
Hi, 
Unlike in other routines, the output of the flux spectroscopies is not formatted:
image

It would be nice to format the output removing unnecessary decimals, using separators.

Additionally, the visibility of the fit trace cannot be toogled. Considering the it often fails, it would be nice to be able to hide it.

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #473.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Review by aorgazf — CHANGES_REQUESTED** [review]
Hi @andrea-pasquale,
Thanks for taking care of this issue.
I've tried the changes implemented so far. Could you please introduce comma separators on all numbers, and add the missing units of measurement.
image

**Comment by aorgazf** [comment]
Hi @andrea-pasquale,
Another suggestion for improvement. 
These parameters are not clear what they are:Xi
d
g
Ec
Ej
bare_resonator_frequency
f_qs
f_r_offset
C_ii

I would add a description before its symbol: `Inductive Energy Ej`
For consistency I would also replace bare_resonator_frequency with `Resonator Bare Frequency`

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by DavidSarlle** [comment]
@AlejandroSopena can you modify the name of the fitted parameters to be more explicit and specify the units in order to approve the PR? I think is better if you do it,  because you know the theory better than me.

**Comment by andrea-pasquale** [comment]
> @AlejandroSopena can you modify the name of the fitted parameters to be more explicit and specify the units in order to approve the PR? I think is better if you do it, because you know the theory better than me.

@DavidSarlle, we can also go ahead and merge this PR and address this point later. @Edoardo-Pedicillo just opened #509.

**Comment by AlejandroSopena** [comment]
I can do it this evening. Sorry for not doing it earlier.

**Comment by andrea-pasquale** [comment]
@AlejandroSopena it seems that tests are not passing anymore. Could you please have a look?

**Comment by andrea-pasquale** [comment]
@scarrazza also this PR is ready to merge as soon as we have a second review.

**Comment by DavidSarlle** [comment]
@andrea-pasquale If i am not wrong, this PR does not contain the latest code from main. The flux routines does not contain the latest changes introduced by @stavros11 (crosstalk Matrix)

**Comment by andrea-pasquale** [comment]
Thanks @DavidSarlle.
I know that this PR is missing the crosstalk Matrix.
There are no conflicts so I'm guessing that everything should be fine.
I think that we can merge it as it is.

**Review by DavidSarlle — APPROVED** [review]

**Comment by DavidSarlle** [comment]
I have approved the PR @andrea-pasquale I used to test the routine after merging main just in case, but reviewing the code it should work as it is and as you said, there are no conflicts. So, let's merge it and check.

**Pull request merged**
