### PR TITLE
Simplify action builder + fix tests

### PR DESCRIPTION
**Pull request by andrea-pasquale**
This PR includes a few improvements to the `ActionBuilder` that I suggested when reviewing #239.
@wilkensJ let me know if everything works as expected and if so feel free to merge this PR to #239.

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by wilkensJ** [comment]
Looks good! My tests still go through locally on my laptop.

**Review by wilkensJ — APPROVED** [review]
Top!

**Comment by andrea-pasquale** [comment]
I was able to fix the problem regarding tests on windows. Now it seems that there are other errors involving tests.
Probably there is something which is not working. Feel free to merge this PR and fix those issues directly in your PR.

**Comment by wilkensJ** [comment]
The tests are going through! Very good. Thank you Andrea.

**Comment by andrea-pasquale** [comment]
Great. Thanks for fixing them. I suggest to merge this PR as soon as possible.

**Pull request merged**
