### PR TITLE
Bell protocol

### PR DESCRIPTION
**Pull request by andrea-pasquale**
This PR implements the following:
- CHSH as protocol (with pulses or circuits)
- ReadoutMitigationMatrix protocol  which can be used by itself or directly in CHSH by setting `apply_readout_mitigation=True`

TODO:
- [x] Implement readout error mitigation
- [x] Run on hardware

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
This PR should be ready to review now.
We are still not able see Bell with qw5q_gold, I have gone over the code with @igres26 and it seems to be working as expected on paper.
I won't be able to follow up this PR during the next two weeks since I will be on vacations. As soon as I'm back I can implement the suggested changes.

**Comment by DavidSarlle** [comment]
@andrea-pasquale I think you need to merge main into this PR in order to have the latest changes. An error is raised because of the latest renaming of the dump function to dump_runcard in the platform.

Traceback (most recent call last):
  File "/home/users/david.fuentes/.conda/envs/auto/bin/qq", line 6, in <module>
    sys.exit(command())
  File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/_base.py", line 58, in command
    builder = ActionBuilder(card, folder, force, update=update)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/builders.py", line 38, in __init__
    self.meta = self._prepare_output(runcard)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/builders.py", line 76, in _prepare_output
    self.platform.dump(self.folder / PLATFORM)
AttributeError: 'Platform' object has no attribute 'dump'

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale I think you need to merge main into this PR in order to have the latest changes. An error is raised because of the latest renaming of the dump function to dump_runcard in the platform.
> 
> Traceback (most recent call last): File "/home/users/david.fuentes/.conda/envs/auto/bin/qq", line 6, in sys.exit(command()) File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1130, in **call** return self.main(*args, **kwargs) File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/users/david.fuentes/.conda/envs/auto/lib/python3.9/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/_base.py", line 58, in command builder = ActionBuilder(card, folder, force, update=update) File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/builders.py", line 38, in **init** self.meta = self._prepare_output(runcard) File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/builders.py", line 76, in _prepare_output self.platform.dump(self.folder / PLATFORM) AttributeError: 'Platform' object has no attribute 'dump'

You are right, I've just merge main now.

**Comment by DavidSarlle** [comment]
@andrea-pasquale thanks for implementing the routine. I have reviewed the code and there are no comments regarding the code, it works as expected and it is very straightforward. Also thanks for implementing the possibility to run the routine using pulses or circuits. But regarding that, the results obtained using the same conditions with pulses and circuits are very different as you can see below:

imagen

imagen

Both executions has been run with the same conditions (qubits, runcard and action parameters). To me seems that there is a source of errors in the circuit execution. Reviewing the code I am pretty sure that there is no problem in the routine and the errors could come from:

1. Transpilation of the circuit into gates and pulses. Maybe we should check it @Simone-Bordoni 
2. Pi/2 pulse characterization. Right now there are no routines specific for characterization of the pi/2 pulses and the transpiler transform circuits into U3 gates that use pi/2 pulses. That could be also a source of errors @igres26 @Simone-Bordoni 

Can you run the same test and see if you obtain the similar results @andrea-pasquale @igres26 @Simone-Bordoni, in order to determine if we have an error in any of the steps mentioned?

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale thanks for implementing the routine. I have reviewed the code and there are no comments regarding the code, it works as expected and it is very straightforward. Also thanks for implementing the possibility to run the routine using pulses or circuits. But regarding that, the results obtained using the same conditions with pulses and circuits are very different as you can see below:
> 
> imagen
> 
> imagen
> 
> Both executions has been run with the same conditions (qubits, runcard and action parameters). To me seems that there is a source of errors in the circuit execution. Reviewing the code I am pretty sure that there is no problem in the routine and the errors could come from:
> 
> 1. Transpilation of the circuit into gates and pulses. Maybe we should check it @Simone-Bordoni
> 2. Pi/2 pulse characterization. Right now there are no routines specific for characterization of the pi/2 pulses and the transpiler transform circuits into U3 gates that use pi/2 pulses. That could be also a source of errors @igres26 @Simone-Bordoni
> 
> Can you run the same test and see if you obtain the similar results @andrea-pasquale @igres26 @Simone-Bordoni, in order to determine if we have an error in any of the steps mentioned?

@DavidSarlle I found a bug in the code that was executing the readout mitigation matrix using circuits.
Here is the current output:

image

I believe that now the behavior is more or less consistent. There are some differences but I think that they are expected.

**Comment by andrea-pasquale** [comment]
@stavros11 if possible I would like to merge also this PR given that it has been ready for a while and now the fridge is warm so we won't be able to test it.
Could you please have a look whenever you have time?

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
